<option value="Keuskupan Agung Kuala Lumpur">Keuskupan Agung Kuala Lumpur</option>
<option value="Keuskupan Pinang">Keuskupan Pinang</option>
<option value="Keuskupan Melaka-Johor">Keuskupan Melaka-Johor</option>
<option value="Keuskupan Agung Kota Kinabalu">Keuskupan Agung Kota Kinabalu</option>
<option value="Keuskupan Keningau">Keuskupan Keningau</option>
<option value="Keuskupan Sandakan">Keuskupan Sandakan</option>
<option value="Keuskupan Agung Kuching">Keuskupan Agung Kuching</option>
<option value="Keuskupan Miri">Keuskupan Miri</option>
<option value="Keuskupan Sibu">Keuskupan Sibu</option>